version: 0.0
os: linux
files:
   source: /home.phtml
   destination: /opt/codetest  
permissions:
  - object: /opt/codetest
    pattern: "**"
    owner: root
    group: root
    mode: 664 
    type:
      - file
  - object: /opt/codetest
    pattern: "**"
    owner: root
    group: root
    mode: 775
    type:
      - directory
