version: 0.0
os: linux
files:
   source: /home.phtml
   destination: /var/www/html/morselo/app/design/frontend/morselo/default/template/page
permissions:
  - object: /var/www/html/morselo/app/design/frontend/morselo/default/template/page
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 664
    type:
      - file
  - object: /var/www/html/morselo/app/design/frontend/morselo/default/template/page
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 775
    type:
      - directory
