<?php
//
//if(!Mage::helper('customer')->isLoggedIn()) {
//    Mage::getSingleton('customer/session')
//        ->setBeforeAuthUrl($this->getUrl('taste_test_location'));
//    echo '<a href="'.Mage::getUrl('customer/account/login').'">Avail the taste Test Here</a>';
// }else{?>
<!--    <a href="--><?//= $this->getUrl('taste_test_location');?><!--">Avail the taste Test Here </a>-->
<?php //}
//?>

<div class="containerMain auto">
<section class="section mainframe">
    <div class="newsSlider ptop_adjst auto slider1" >
        <div class="insd_newsSlider auto ">
            <ul class="news-slider">
                <li>
                    <div class="slider" style="background-image: url(<?php echo $this->getSkinUrl('images/homeslider_01.jpg');?>)">
                        <div class="inner auto">
                            <div class="slider-cont  auto">
<!--
                                <h2>Introducing <span><img src="<? echo $this->getSkinUrl('images/logo-text.png');?>"/></span></h2>
                                <p>A new food. An experience of taste sensations wrapped in convenience. A must try!</p>
-->
                                <p><a class="button_s1" href="<?= $this->getUrl('menu#offer');?>">Exciting Offers</a></p>
<!--                                <a href="javascript:void(0);" onclick="moreabout()">Know more about morselo</a>-->
                            </div>
                        </div>
                    </div>
                </li>

                <li>
                    <div class="slider" style="background-image: url(<?php echo $this->getSkinUrl('images/homeslider_02.jpg');?>)">
                        <div class="inner auto">
                            <div class="slider-cont  auto">
<!--
                                <h2>Introducing <span><img src="<? echo $this->getSkinUrl('images/logo-text.png');?>"/></span></h2>
                                <p>Temptations that readily melt in your mouth.<br />&nbsp;</p>
-->
                                <p><a class="button_s1" href="<?= $this->getUrl('menu#offer');?>">Exciting Offers</a></p>
<!--                                <a href="javascript:void(0);" onclick="moreabout()">Know more about morselo</a>-->
                            </div>
                        </div>
                    </div>
                </li>
                
                <li>
                    <div class="slider" style="background-image: url(<?php echo $this->getSkinUrl('images/homeslider_03.jpg');?>)">
                        <div class="inner auto">
                            <div class="slider-cont  auto">
<!--
                                <h2>Introducing <span><img src="<? echo $this->getSkinUrl('images/logo-text.png');?>"/></span></h2>
                                <p>Food that delivers amazing flavours without interfering with your work or leisure.</p>
-->
                                <p><a class="button_s1" href="<?= $this->getUrl('menu#offer');?>">Exciting Offers</a></p>
<!--                                <a href="javascript:void(0);" onclick="moreabout()">Know more about morselo</a>-->
                            </div>
                        </div>
                    </div>
                </li>
              <?php /*
                <li>
                    <div class="slider" style="background-image: url(<?php echo $this->getSkinUrl('images/slider_04.jpg');?>)">
                        <div class="inner auto">
                            <div class="slider-cont  auto">
                                <h2>Introducing Morselo!</h2>
                                <p>A new food. A temptation with a secret inside. A must try. A bucket list item !</p>
                                <p><a href="<?= $this->getUrl('taste-test');?>?reAuth=2">Taste test</a></p>
                                <a href="javascript:void(0);" onclick="moreabout()">Know more about morselo</a>
                            </div>
                        </div>
                    </div>
                </li>
                <?php */ ?>
            </ul>
        </div><!--insd_newsSlider-->
            <a class="scroll-bottom" href="#footer"></a>
    </div><!-- inside news slider -->
       <div class="newsSlider ptop_adjst auto slider2" >
        <div class="insd_newsSlider auto ">
            <ul class="news-slider">
                 <li class="mob_slider">
                    <div class="slider" style="background-image: url(<?php echo $this->getSkinUrl('images/food1.jpg');?>)">
                        <div class="inner auto">
                            <div class="slider-cont  auto">
<!--
                                <h2>Introducing <span><img src="<? echo $this->getSkinUrl('images/food2.jpg');?>"/></span></h2>
                                <p>A new food. An experience of taste sensations wrapped in convenience. A must try!</p>
-->
                                <p><a class="button_s1" href="<?= $this->getUrl('menu#offer');?>">Exciting Offers</a></p>
<!--                                <a href="javascript:void(0);" onclick="moreabout()">Know more about morselo</a>-->
                            </div>
                        </div>
                    </div>
                </li>
                <li class="mob_slider">
                    <div class="slider" style="background-image: url(<?php echo $this->getSkinUrl('images/food2.jpg');?>)">
                        <div class="inner auto">
                            <div class="slider-cont  auto">
<!--
                                <h2>Introducing <span><img src="<? echo $this->getSkinUrl('images/logo-text.png');?>"/></span></h2>
                                <p>A new food. An experience of taste sensations wrapped in convenience. A must try!</p>
-->
                                <p><a class="button_s1" href="<?= $this->getUrl('morselo-offers');?>">Exciting Offers</a></p>
<!--                                <a href="javascript:void(0);" onclick="moreabout()">Know more about morselo</a>-->
                            </div>
                        </div>
                    </div>
                </li>
                <li class="mob_slider">
                    <div class="slider" style="background-image: url(<?php echo $this->getSkinUrl('images/food3.jpg');?>)">
                        <div class="inner auto">
                            <div class="slider-cont  auto">
<!--
                                <h2>Introducing <span><img src="<? echo $this->getSkinUrl('images/logo-text.png');?>"/></span></h2>
                                <p>A new food. An experience of taste sensations wrapped in convenience. A must try!</p>
-->
                                <p><a class="button_s1" href="<?= $this->getUrl('menu#offer');?>">Exciting Offers</a></p>
<!--                                <a href="javascript:void(0);" onclick="moreabout()">Know more about morselo</a>-->
                            </div>
                        </div>
                    </div>
                </li><?php /*
                <li>
                    <div class="slider" style="background-image: url(<?php echo $this->getSkinUrl('images/slider_04.jpg');?>)">
                        <div class="inner auto">
                            <div class="slider-cont  auto">
                                <h2>Introducing Morselo!</h2>
                                <p>A new food. A temptation with a secret inside. A must try. A bucket list item !</p>
                                <p><a href="<?= $this->getUrl('taste-test');?>?reAuth=2">Taste test</a></p>
                                <a href="javascript:void(0);" onclick="moreabout()">Know more about morselo</a>
                            </div>
                        </div>
                    </div>
                </li>
                <?php */ ?>
            </ul>
        </div><!--insd_newsSlider-->
            <a class="scroll-bottom" href="#footer"></a>
    </div><!-- inside news slider -->
</section>
    <section class="ai_mainwrapper">
        <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/morselo-footer.phtml')->toHtml(); ?>
<link href="<? echo $this->getSkinUrl('bxslider/jquery.bxslider.css');?>" rel="stylesheet" type="text/css">
<script src="<? echo $this->getSkinUrl('js/jquery.min.js');?>"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-scrollTo/2.1.0/jquery.scrollTo.min.js"></script>
<script src="<? echo $this->getSkinUrl('bxslider/jquery.bxslider.js');?>"></script>
<script src="<? echo $this->getSkinUrl('js/smartscroll.min.js');?>"></script>
<script src="<? echo $this->getSkinUrl('js/custom.js');?>"></script>
<script>
    jQuery(document).ready(function(){
        jQuery('.news-slider,.cmn-news-slider').bxSlider({
            controls:false,
            mode:'fade',
            auto:true,
            speed:1000,
            touchEnabled:false
        });
		jQuery('.customer_service').click(function () {
         var WH = jQuery(window).height();  
  var SH = jQuery('body').prop("scrollHeight");
  jQuery('html, body').stop().animate({scrollTop: SH-WH}, 1000);
    });
    });
</script>
